WHITESPACE  = _{ " " | "\t" | "\n" }

plus = { "+" }
minus = { "-" }
div = { "/" }
times = { "*" }
pow = {"^"}
neg = {"-"}
deref = {"*"}
reference = {"@"}
fact = {"!"}
access = {"."}

infix = _{plus | minus | div | times | pow | access }
prefix = _{ neg | deref | reference}
postfix = _{ fact }

primary = { value | "(" ~ operation ~ ")"}
operation = {prefix* ~ primary ~ postfix* ~ (infix ~ prefix* ~ primary ~ postfix*)*}

call = {id ~ (tuple | id)}
expr = { call | operation }
