alpha = { 'a'..'z' | 'A'..'Z' }
zero = { "0" }

decimal_digit = { '0'..'9'}
binary_digit = { "0" | "1" }
hex_digit = { '0'..'9' | 'A'..'F'}

keyword = {"let"}
id = @{ !decimal_digit ~ !keyword ~ (alpha | decimal_digit)+ }

default_number = { decimal_digit+ }
decimal_number = { "0d" ~ decimal_digit+ }
binary_number = { "0b" ~ binary_digit+ }
hex_number = { "0x" ~ hex_digit+ }

character = { "\'" ~ alpha ~ "\'"}

tuple = { "(" ~ expr ~ ("," ~ value)* ~ ")" }

value = { decimal_number | binary_number
      	  | hex_number | character
	  | default_number
	  | id
	  | tuple
        }